import alpha from '../../lib/alpha';
import { Colors } from '../Theme';

// See: https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors
export default ({ base, misc }: Colors) => ({
  'editor.foreground': base.fg,
  'editor.background': base.bg,
  'editorLineNumber.foreground': misc.comment,
  'editorLineNumber.activeForeground': base.cyan,
  'editorCursor.foreground': base.cyan,
  'editor.selectionBackground': misc.selection,
  'editor.selectionHighlightBorder': base.orange,
  'editor.inactiveSelectionBackground': null,
  'editor.wordHighlightBackground': alpha(base.cyan, 50),
  'editor.wordHighlightStrongBackground': alpha(base.green, 50),
  'editor.findMatchBackground': alpha(base.orange, 80),
  'editor.findMatchHighlightBackground': alpha(base.white, 40),
  'editor.findRangeHighlightBackground': misc.lineHighlight,
  'editor.hoverHighlightBackground': misc.bgDarker,
  'editor.lineHighlightBackground': misc.lineHighlight,
  'editor.lineHighlightBorder': null,
  'editorLink.activeForeground': base.cyan,
  'editor.rangeHighlightBackground': alpha(base.purple, 15),
  'editorWhitespace.foreground': misc.nonText,
  'editorIndentGuide.background': misc.nonText,
  'editorIndentGuide.activeBackground': misc.activeBorder,
  'editorRuler.foreground': null,
  'editorCodeLens.foreground': misc.comment,
  'editorBracketMatch.background': null,
  'editorBracketMatch.border': null,
  'editorOverviewRuler.border': misc.bgDarker,
  'editorOverviewRuler.findMatchForeground': null,
  'editorOverviewRuler.rangeHighlightForeground': null,
  'editorOverviewRuler.selectionHighlightForeground': base.orange,
  'editorOverviewRuler.wordHighlightForeground': base.cyan,
  'editorOverviewRuler.wordHighlightStrongForeground': base.green,
  'editorOverviewRuler.modifiedForeground': alpha(base.orange, 80),
  'editorOverviewRuler.addedForeground': alpha(base.green, 80),
  'editorOverviewRuler.deletedForeground': alpha(base.red, 80),
  'editorOverviewRuler.errorForeground': alpha(base.red, 80),
  'editorOverviewRuler.warningForeground': alpha(base.yellow, 80),
  'editorOverviewRuler.infoForeground': alpha(base.cyan, 80),
  'editorError.foreground': base.red,
  'editorError.border': null,
  'editorWarning.foreground': base.cyan,
  'editorWarning.border': null,
  'editorGutter.background': null,
  'editorGutter.modifiedBackground': alpha(base.orange, 80),
  'editorGutter.addedBackground': alpha(base.green, 80),
  'editorGutter.deletedBackground': alpha(base.red, 80)
});
